import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import MedicalForm from "@/components/MedicalForm";
import { GetServerSideProps, NextApiRequest, NextApiResponse } from "next";
import { createSupaClient } from "@/service/supa";
import { createClient } from "@supabase/supabase-js";
import { clinic } from "@/types/common";
import { Paper } from "@mui/material";
import styled from "@emotion/styled";
import Link from "next/link";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

const StyledPaper = styled(Paper)`
  padding: 1rem;
  width: 100%;
  cursor: pointer;
`;

const Wrapper = styled.div`
  min-width: 500px;
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 1rem;
  flex-direction: column;
`;

interface HomeProps {
  clinic: clinic[];
}

export default function Home({ clinic }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Wrapper>
          {clinic.map((clinic) => (
            <StyledPaper
              key={clinic.id}
              elevation={2}
              onClick={() => {
                window.location.href = `/${clinic.name}`;
              }}
            >
              <Link href={`/${clinic.name}`}>{clinic.name}</Link>
            </StyledPaper>
          ))}
        </Wrapper>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async (
  context
) => {
  try {
    const supabase = createSupaClient();

    let { data: Clinic } = await supabase.from("Clinic").select("*");

    return {
      props: {
        clinic: Clinic || [],
      },
    };
  } catch {
    return {
      props: {
        clinic: [],
      },
    };
  }
};
