export const prescriptionPdfConfigEn = {
  margin: 12,
  spacing: 8,
  khFont: "Khmer",
  enFont: "Helvetica",
  titleFont: "Helvetica",
  titleFontSize: 14,
  normalFontSize: 12,
  subTitleFontSize: 14,
  smallFontSize: 10,
  content: {
    titleTextLine1: "First Line",
    titleTextLine2: "Second Line",
    nameLabel: "Name:",
    sexLabel: "Sex:  ",
    sexValue: {
      male: "Male",
      female: "Female",
    },
    ageLabel: "Age:  ",
    diagnosisLabel: "Diagnosis:  ",
    prescriptionLabel: {
      title: "Prescription",
      medicine: "Medicine",
      amount: "Amount",
      usage: "Usage",
    },
    doctorTitle: "Dr.",
    bottomText: "This is a sample text for the bottom of the page.",
    address: "test",
  },
};

export const invoicePdfConfigEn = {
  margin: 13,
  spacing: 8,
  khFont: "Khmer",
  enFont: "Helvetica",
  fancyKhFont: "Fancy-Khmer",
  titleFontSize: 16,
  normalFontSize: 12,
  content: {
    titleTextLine1: "មន្ទីរពហុព្យាបាល សុខសាន្ត",
    titleTextLine2: "SOK SAN POLYCLINIC",
    nameLabel: "Name: ",
    invoiceLabel: "Invoice:",
    genderLabel: "Gender: ",
    sexValue: {
      male: "Male",
      female: "Female",
    },
    ageLabel: "Age: ",
    dateLabel: "Date: ",
    prescriptionLabel: {
      header: [
        { header: "No", dataKey: "No" },
        { header: "Description", dataKey: "Description" },
        { header: "Qty", dataKey: "Qty" },
        { header: "Unit Price", dataKey: "Unit Price" },
        { header: "Amount", dataKey: "Amount" },
      ],
      totalLabel: "Total",
    },
    header: "",
    logoText: "មន្ទីរពហុព្យាបាល សុខសាន្ត\nSOK SAN POLYCLINIC",
    SignatureLabelEn: "Accountant Signature",
    SignatureLabelKh: "ហត្ថលេខា បេឡា",
    footer: "",
  },
};

export const prescriptionPdfConfigKh = {
  margin: 45,
  spacing: 8,
  khFont: "Khmer",
  enFont: "Helvetica",
  titleFont: "Fancy-Khmer",
  titleFontSize: 16,
  normalFontSize: 12,
  subTitleFontSize: 14,
  smallFontSize: 10,
  content: {
    titleTextLine1: "មន្ទីរពហុព្យាបាល សុខសាន្ត",
    titleTextLine2: "SOK SAN POLYCLINIC",
    nameLabel: "ឈ្មោះ:  ",
    sexLabel: "ភេទ:  ",
    sexValue: {
      male: "ប្រុស",
      female: "ស្រី",
    },
    ageLabel: "អាយុ:  ",
    diagnosisLabel: "រោគវិនិច្ឆ័យ:   ",
    prescriptionLabel: {
      title: "វេជ្ជបញ្ជា",
      medicine: "ឈ្មោះថ្នាំ",
      amount: "ចំនួន",
      usage: "ការប្រើប្រាស់",
    },
    doctorTitle: "វេជ្ជ.",
    bottomText: "សូមយកវេជ្ជបញ្ជានេះមកវិញ ពេលមកពិនិត្យលេីកក្រោយ",
    address:
      "ផ្ទះលេខ ៧៦៨, ផ្លូវជាតិលេខ ៥ គីឡូម៉ែត្រលេខ ៦, ខណ្ឌ ឬស្សីកែវ រាជធានីភ្នំពេញ Tel: 010/017 89 22 89",
  },
};

export const invoicePdfConfigKh = {
  margin: 24,
  spacing: 8,
  khFont: "Khmer",
  enFont: "Helvetica",
  fancyKhFont: "Fancy-Khmer",
  titleFontSize: 14,
  normalFontSize: 10,
  content: {
    titleTextLine1: "វិក្ក័យបត្រ / Invoice",
    titleTextLine2: "ឈ្មោះ / Name:",
    nameLabel: "ឈ្មោះ / Name: ",
    invoiceLabel: "លេខរៀងវិក្ក័យបត្រ:",
    genderLabel: "ភេទ / Gender: ",
    sexValue: {
      male: "Male",
      female: "Female",
    },
    ageLabel: "អាយុ / Age: ",
    dateLabel: "ថ្ងៃចេញវិក្ក័យបត្រ: ",
    prescriptionLabel: {
      header: [
        { header: "លរ\n ", dataKey: "No" },
        { header: "បរិយាយមុខទំនិញ\nDescription", dataKey: "Description" },
        { header: "បរិមាណ\nQty", dataKey: "Qty" },
        { header: "តម្លៃរាយ\nUnit Price", dataKey: "unitPrice" },
        { header: "តម្លៃទំនិញ\nAmount", dataKey: "Amount" },
      ],
      totalLabel: "តម្លៃសរុប",
    },
    SignatureLabelEn: "Accountant Signature",
    SignatureLabelKh: "ហត្ថលេខា បេឡា",
    header: "ព្រះរាជាណាចក្រកម្ពុជា\nជាតិ សាសនា ព្រះមហាក្សត្រ",
    logoText: "មន្ទីរពហុព្យាបាល សុខសាន្ត\nSOKSAN POLYCLINIC",
    footer:
      "ផ្ទះលេខ ៧៦៨, ផ្លូវជាតិលេខ ៥ គីឡូម៉ែត្រលេខ ៦, ខណ្ឌ ឬស្សីកែវ រាជធានីភ្នំពេញ (ទល់មុខរោងចក្រ កូកាកូឡា)\nលេខទូរស័ព្ទ 010 89 22 89, 017 89 22 89, 012 99 37 22",
  },
};

export const Month = [
  "",
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];
